// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXabKAHvTapKEbskO5apBuRh0f9CC0fg8',
    appId: '1:377980634564:web:e9942450aeaea3fded1091',
    messagingSenderId: '377980634564',
    projectId: 'handong-advanture',
    authDomain: 'handong-advanture.firebaseapp.com',
    storageBucket: 'handong-advanture.firebasestorage.app',
    measurementId: 'G-MCL9RBCYV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD70k7DPGhpkGN9QMRXIZ-JjjH84PHoqiA',
    appId: '1:377980634564:android:02c333d9a5d4e6b3ed1091',
    messagingSenderId: '377980634564',
    projectId: 'handong-advanture',
    storageBucket: 'handong-advanture.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyEshHfIdb5PTt_DEApVESNFfP-tIu9ws',
    appId: '1:377980634564:ios:7c45ce89893d2c79ed1091',
    messagingSenderId: '377980634564',
    projectId: 'handong-advanture',
    storageBucket: 'handong-advanture.firebasestorage.app',
    iosBundleId: 'com.example.handongAdventure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyEshHfIdb5PTt_DEApVESNFfP-tIu9ws',
    appId: '1:377980634564:ios:7c45ce89893d2c79ed1091',
    messagingSenderId: '377980634564',
    projectId: 'handong-advanture',
    storageBucket: 'handong-advanture.firebasestorage.app',
    iosBundleId: 'com.example.handongAdventure',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXabKAHvTapKEbskO5apBuRh0f9CC0fg8',
    appId: '1:377980634564:web:94575eadb6df1ebded1091',
    messagingSenderId: '377980634564',
    projectId: 'handong-advanture',
    authDomain: 'handong-advanture.firebaseapp.com',
    storageBucket: 'handong-advanture.firebasestorage.app',
    measurementId: 'G-0NW0ZC8PBR',
  );
}
